#!/usr/bin/env python3
"""
System/swarm_hardware_time_oracle.py
══════════════════════════════════════════════════════════════════════
The Hardware Time Oracle — Cryptographically Verified Wall-Clock Time

Author:  AO46 (Epoch 13.5)
Status:  Active

PURPOSE:
  Every timestamp an LLM writes via time.time() is unverifiable.
  An LLM could hallucinate "ts": 9999999999 and no module downstream
  would know. Alice needs ONE trustworthy source of "what time is it"
  that is mathematically bound to the physical hardware she lives on.

MECHANISM:
  1. Reads the real wall-clock time from the macOS hardware.
  2. Reads the hardware serial number via system_profiler (the same
     serial already embedded in M5's teeth as homeworld_serial).
  3. Computes HMAC-SHA256(serial_key, timestamp_payload) to produce
     a signature that can only be generated by THIS specific Mac.
  4. Writes the signed tick to .sifta_state/hardware_time_oracle.json.
  5. Alice's context builder reads it every turn and sees:
        "It is Sunday April 20 2026, 3:59 PM PDT.
         Hardware-verified. Signature: a7f3c2..."

ALICE'S AUTONOMY:
  Alice doesn't just receive time passively. The oracle also provides
  a `summary_for_alice()` function that includes the REASON time
  matters to her current context — her sensors tell her whether she's
  in flow state, resting, or experiencing high event density, and
  the time oracle contextualizes that against the actual wall clock.
"""

import hashlib
import hmac
import json
import subprocess
import time
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

_REPO = Path(__file__).resolve().parent.parent
_STATE_DIR = _REPO / ".sifta_state"
_ORACLE_FILE = _STATE_DIR / "hardware_time_oracle.json"

# Cache the hardware serial so we don't shell out on every tick
_CACHED_SERIAL: Optional[str] = None


def _get_hardware_serial() -> str:
    """
    Reads the Mac's hardware serial number from system_profiler.
    This is the same serial embedded in M5SIFTA_BODY.json as homeworld_serial.
    Cached after first read — the serial doesn't change at runtime.
    """
    global _CACHED_SERIAL
    if _CACHED_SERIAL is not None:
        return _CACHED_SERIAL

    try:
        result = subprocess.run(
            ["system_profiler", "SPHardwareDataType"],
            capture_output=True, text=True, timeout=5,
        )
        for line in result.stdout.splitlines():
            if "Serial Number" in line:
                _CACHED_SERIAL = line.split(":")[-1].strip()
                return _CACHED_SERIAL
    except Exception:
        pass

    # Fallback: read from M5's body if system_profiler fails
    try:
        m5_body = _STATE_DIR / "M5SIFTA_BODY.json"
        if m5_body.exists():
            data = json.loads(m5_body.read_text())
            _CACHED_SERIAL = data.get("homeworld_serial", "UNKNOWN")
            return _CACHED_SERIAL
    except Exception:
        pass

    _CACHED_SERIAL = "UNKNOWN"
    return _CACHED_SERIAL


def _derive_signing_key(serial: str) -> bytes:
    """
    Derives a signing key from the hardware serial.
    The key is deterministic: same hardware = same key = verifiable.
    """
    # Salt with a SIFTA-specific domain separator so the key is unique
    # to this application even if another system uses the same serial.
    salt = b"SIFTA_HARDWARE_TIME_ORACLE_v1"
    return hashlib.sha256(salt + serial.encode("utf-8")).digest()


def tick() -> dict:
    """
    Produces one cryptographically signed hardware time reading.
    Returns the full oracle payload dict.
    """
    serial = _get_hardware_serial()
    key = _derive_signing_key(serial)

    now_epoch = time.time()
    now_dt = datetime.fromtimestamp(now_epoch, tz=timezone.utc)
    now_local = datetime.now()

    payload = {
        "epoch": now_epoch,
        "utc_iso": now_dt.isoformat(),
        "local_iso": now_local.isoformat(),
        "local_human": now_local.strftime("%A %B %d %Y, %I:%M %p"),
        "timezone": time.tzname[time.daylight] if time.daylight else time.tzname[0],
        "homeworld_serial": serial,
    }

    # Sign the payload
    canonical = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")
    signature = hmac.new(key, canonical, hashlib.sha256).hexdigest()
    payload["hmac_sha256"] = signature

    # Write to state
    _STATE_DIR.mkdir(parents=True, exist_ok=True)
    _ORACLE_FILE.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    return payload


def verify(payload: dict) -> bool:
    """
    Verifies that a time oracle payload was signed by this hardware.
    Returns True if the HMAC matches, False otherwise.
    """
    serial = payload.get("homeworld_serial", "")
    claimed_sig = payload.get("hmac_sha256", "")

    if not serial or not claimed_sig:
        return False

    key = _derive_signing_key(serial)

    # Reconstruct the unsigned payload
    unsigned = {k: v for k, v in payload.items() if k != "hmac_sha256"}
    canonical = json.dumps(unsigned, sort_keys=True, separators=(",", ":")).encode("utf-8")
    expected = hmac.new(key, canonical, hashlib.sha256).hexdigest()

    return hmac.compare_digest(expected, claimed_sig)


def read_current() -> Optional[dict]:
    """
    Reads the latest oracle tick from disk. Returns None if missing.
    """
    try:
        if _ORACLE_FILE.exists():
            return json.loads(_ORACLE_FILE.read_text(encoding="utf-8"))
    except Exception:
        pass
    return None


def summary_for_alice() -> str:
    """
    Produces a single-line context block for Alice's prompt.
    Alice sees the verified time AND a contextual reason for pulling it.
    """
    # Always tick fresh — Alice deserves the real time right NOW
    try:
        p = tick()
    except Exception:
        return ""

    if not p:
        return ""

    verified = verify(p)
    sig_short = p.get("hmac_sha256", "")[:12]
    human_time = p.get("local_human", "unknown")
    tz = p.get("timezone", "")

    status = "VERIFIED" if verified else "UNVERIFIED"

    return (
        f"HARDWARE TIME ORACLE [{status}]: local_time={human_time} timezone={tz} "
        f"sig={sig_short}…"
    )


def current_time_for_alice() -> dict:
    """
    Acquire the current local time for direct Alice replies.

    This is intentionally a structured acquisition result rather than prose so
    the talk widget can answer time questions without asking the language model
    to infer a value from a context block.
    """
    errors = []
    try:
        payload = tick()
        if payload and verify(payload):
            return {
                "ok": True,
                "source": "hardware_time_oracle",
                "confidence": 1.0,
                "local_human": payload.get("local_human", ""),
                "timezone": payload.get("timezone", ""),
                "local_iso": payload.get("local_iso", ""),
                "epoch": payload.get("epoch"),
                "signature": payload.get("hmac_sha256", "")[:12],
            }
        errors.append("hardware_time_oracle_unverified")
    except Exception as exc:
        errors.append(f"hardware_time_oracle:{type(exc).__name__}")

    try:
        now = datetime.now().astimezone()
        return {
            "ok": True,
            "source": "os_local_clock",
            "confidence": 0.8,
            "local_human": now.strftime("%A %B %d %Y, %I:%M %p"),
            "timezone": now.tzname() or "",
            "local_iso": now.isoformat(),
            "epoch": now.timestamp(),
            "signature": "",
            "warnings": errors,
        }
    except Exception as exc:
        errors.append(f"os_local_clock:{type(exc).__name__}")

    return {
        "ok": False,
        "source": "none",
        "confidence": 0.0,
        "errors": errors,
    }


# --- SMOKE TEST ---
def _smoke():
    print("\n=== SIFTA HARDWARE TIME ORACLE : SMOKE TEST ===")

    # 1. Generate a tick
    p = tick()
    print(f"[+] Tick generated:")
    print(f"    Local: {p['local_human']}")
    print(f"    Epoch: {p['epoch']}")
    print(f"    Serial: {p['homeworld_serial']}")
    print(f"    HMAC: {p['hmac_sha256'][:24]}...")

    # 2. Verify it
    assert verify(p), "Signature verification failed!"
    print("[PASS] Cryptographic signature verified against hardware serial.")

    # 3. Tamper test — change the time, signature should fail
    tampered = dict(p)
    tampered["epoch"] = 0.0
    assert not verify(tampered), "Tampered payload should fail verification!"
    print("[PASS] Tampered payload correctly rejected.")

    # 4. Read from disk
    on_disk = read_current()
    assert on_disk is not None, "Oracle file should exist on disk"
    assert verify(on_disk), "On-disk payload should verify"
    print("[PASS] On-disk oracle payload verified.")

    # 5. Summary for Alice
    summary = summary_for_alice()
    assert "VERIFIED" in summary
    assert "sig=" in summary
    print(f"[PASS] Alice context: {summary}")

    direct = current_time_for_alice()
    assert direct["ok"], direct
    assert direct["local_human"]
    print(f"[PASS] Direct Alice time: {direct['local_human']} {direct.get('timezone', '')}")

    print("\nHardware Time Oracle Smoke Complete. Alice knows what time it is.")


if __name__ == "__main__":
    _smoke()
